export default {
  autoClearEmptyNode: false,
  zIndex: 4000,
  toolbars: [
    [
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'horizontal',
      '|',
      'forecolor',
      'backcolor',
      '|',
      'paragraph',
      'fontfamily',
      'fontsize',
      'lineheight',
      '|',
      'insertorderedlist',
      'insertunorderedlist',
      '|',
      'removeformat',
      'blockquote',
      '|',
      'indent',
      '|',
      'justifyleft',
      'justifycenter',
      'justifyright',
      'justifyjustify',
      '|',
      'fullscreen',
    ],
  ],
}
